
  name: nodejs-kali-linux
  version: '1.3'
  summary: Simple script to install Node.js inside Kali Linux.
  description: |
    This script is used to install node.js within Kali Linux. 
    
  grade: stable
  confinement: strict 

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
